services:
  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    container_name: task4-back-end
    ports:
      - "5252:5252"
    expose:
      - "5252"
    networks:
      - app-network

  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    container_name: task4-front-end
    ports:
      - "8080:80"
    depends_on:
      - back-end
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
